config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :doses, only: [:destroy]
  resources :cocktails do
    resources :cocktail_tags, only: [:new, :create]
    resources :doses, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :cocktail_tags, dependent: :destroy
  has_many :tags, through: :cocktail_tags
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, allow_blank: false, uniqueness: true
end

app/models/cocktail_tag.rb
class CocktailTag < ApplicationRecord
  belongs_to :cocktail
  belongs_to :tag
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, allow_blank: false, uniqueness: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :cocktail_tags, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktail_tags_controller.rb
class CocktailTagsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @cocktail_tag = CocktailTag.new
  end

  def create
    @tags = Tag.where(id: params[:cocktail_tag][:tag])
    @cocktail = Cocktail.find(params[:cocktail_id])
    @tags.each do |tag|
      CocktailTag.create(cocktail: @cocktail, tag: tag)
    end
    if @tags.empty?
      render :new
    else
      redirect_to cocktail_path(@cocktail)
    end
  end

  private

  def cocktail_tag_params
    params.require(:cocktail_tag).permit(:tag_id)
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: @cocktail)
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @tags = Tag.all
    @tags.each do |tag|
      CocktailTag.create(cocktail: @cocktail, tag: tag)
    end
    # @tag_names = params[:cocktail][:tags]
    # raise
    # @tag_names.each do |tag_name|
    #   tag = Tag.find_by(name: tag_name)
    #   # tag = Tag.create(name: tag_name) unless tag
    #   CocktailTag.create(cocktail: @cocktail, tag: tag_name)
    # end
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredients, :doses, :photo, :tags)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def index
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @doses = Dose.where(cocktail_id: @cocktail)
  # end

  # def show
  #   @dose = Dose.find(params[:id])
  # end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(doses_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "/doses/new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.delete
    redirect_to cocktail_path(@cocktail)
  end

  private

  def doses_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktail_tags_helper.rb
module CocktailTagsHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktail_tags/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Add a new tag</h1>
      <%= simple_form_for [ @cocktail, @cocktail_tag ] do |f| %>
        <%= f.input :tag, collection: Tag.all, input_html: { multiple: true, class: "select2" } %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner" >
  <div class="banner-content">
    <h1>Turn Your Favorite Cocktail Recipes into Your Grocery List</h1>
    <p>Now there is an easier way to get started on actually making those yummy-looking recipes.</p>
    <%= link_to "Add new cocktail", new_cocktail_path, class:"btn btn-cta"%>
  </div>
  <div class="banner-image ">
    <%= image_tag 'cocktail'%>
  </div>
</div>

<div class="container">
  <div class="title-index text-center">
    <h3>POPULAR</h3>
    <h1>Cocktails</h1>
  </div>
  <div class="row">
    <% @cocktails.each do |cocktail|%>
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
        <div class="card-cocktail">
          <div class="card-cocktail-img">
            <%= cl_image_tag cocktail.photo, height: 540, width: 300, crop: :fill, class:"cocktail-img"%>
          </div>
          <div class="card-cocktail-infos">
            <h3><%= link_to cocktail.name, cocktail_path(cocktail) %></h3>
            <div class="card-tags">
              <% cocktail.tags.each do |tag| %>
                <span><%= tag.name %></span>
              <% end %>
              <%= link_to new_cocktail_cocktail_tag_path(cocktail) do %>
                <i class="fa fa-plus"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Create new cocktails</h1>

  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :tags, collection: Tag.all, input_html: { multiple: true, class: "select2" } %>
    <%= f.submit "add a cocktail", class: "btn btn-primary", id: "sweet-alert-demo" %>
  <% end %>

  <%= link_to "Cancel", cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<% # raise %>

<h1>Cocktail <%= @cocktail.name %></h1>

<ul>
  <% @cocktail.doses.each do |dose|%>
    <li>
      <%= dose.description %> <%= dose.ingredient.name %>
      <%= link_to "Delete", dose_path(dose) , method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>
<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

<%= link_to "Add new dose", new_cocktail_dose_path(@cocktail) %>
<%= link_to "Delete", cocktail_path(@cocktail) , method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to "Back to cocktails", cocktails_path %>

app/views/doses/index.html.erb
<h1>Doses for <%= @cocktail.name %></h1>
<ul>
  <% @doses.each do |dose|%>
    <li><%= dose.description %> <%= dose.ingredient.name %></li>
  <% end %>
</ul>

app/views/doses/new.html.erb
<h1>Create doses</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, input_html: { class: 'select2' } %>
  <%= f.submit "add a dose", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back to cocktail", cocktail_path(@cocktail) %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag 'logo.png' %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
<!--     <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
    <%= link_to "Add new cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link", id: "cta"%>
    <%= link_to "Back to cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>

  <!-- Dropdown appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Host</a></li>
          <li><a href="#">Trips</a></li>
          <li><a href="#">Messagese</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>